version: '3'
services:
  nextjs:
    container_name: nextjs-dev
    build: 
      context: ./test-app
    volumes:
      - ./test-app:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
